/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneralConfig = t.iface([], {
  "hypixelApiKey": "string",
  "urchinApiKey": t.opt("string"),
  "shareMetrics": "boolean",
});

export const StaticDiscordConfig = t.iface([], {
  "key": "string",
  "adminIds": t.array("string"),
});

export const PrometheusConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "prefix": "string",
});

export const WebConfig = t.iface([], {
  "enabled": "boolean",
  "port": "number",
  "token": "string",
  "minecraftInstance": t.opt("string"),
});

export const StatsChannelConfig = t.iface([], {
  "id": "string",
  "name": "string",
});

export const StatsChannelsConfig = t.iface([], {
  "enabled": "boolean",
  "updateIntervalMinutes": "number",
  "channels": t.array("StatsChannelConfig"),
  "guildName": t.opt("string"),
  "minecraftInstance": t.opt("string"),
});

export const VerificationRoleConfig = t.iface([], {
  "enabled": "boolean",
  "roleId": "string",
});

export const LevelRole = t.iface([], {
  "type": "string",
  "requirement": t.union("number", "string"),
  "roleId": "string",
});

export const VerificationConfig = t.iface([], {
  "nickname": "string",
  "roles": t.iface([], {
    "verified": "VerificationRoleConfig",
    "guildMember": "VerificationRoleConfig",
    "custom": t.array("LevelRole"),
  }),
  "autoRoleUpdater": t.iface([], {
    "enabled": "boolean",
    "interval": "number",
  }),
});

export const GuildRequirementsThresholds = t.iface([], {
  "bedwarsStars": "number",
  "bedwarsFKDR": "number",
  "skywarsStars": "number",
  "skywarsKDR": "number",
  "duelsWins": "number",
  "duelsWLR": "number",
  "skyblockLevel": "number",
});

export const GuildRequirementsConfig = t.iface([], {
  "enabled": "boolean",
  "requirements": "GuildRequirementsThresholds",
  "autoAccept": t.opt("boolean"),
});

export const InactivityConfig = t.iface([], {
  "enabled": "boolean",
  "maxDays": "number",
  "channelIds": t.array("string"),
});

export const SkyblockEventsConfig = t.iface([], {
  "enabled": "boolean",
  "notifiers": t.opt(t.iface([], {
    [t.indexKey]: "boolean",
  })),
  "customTimes": t.opt(t.iface([], {
    [t.indexKey]: t.array("string"),
  })),
});

export const HypixelUpdatesConfig = t.iface([], {
  "enabled": "boolean",
  "hypixelNews": t.opt("boolean"),
  "statusUpdates": t.opt("boolean"),
  "skyblockVersion": t.opt("boolean"),
  "alphaPlayerCount": t.opt("boolean"),
  "pollIntervalMinutes": t.opt("number"),
  "alphaCheckIntervalMinutes": t.opt("number"),
});

export const BridgeConfig = t.iface([], {
  "id": "string",
  "minecraftInstanceNames": t.array("string"),
  "discord": t.iface([], {
    "publicChannelIds": t.array("string"),
    "officerChannelIds": t.array("string"),
  }),
});

export const ApplicationConfig = t.iface([], {
  "version": t.lit(2),
  "general": "GeneralConfig",
  "discord": "StaticDiscordConfig",
  "prometheus": "PrometheusConfig",
  "web": t.opt("WebConfig"),
  "statsChannels": t.opt("StatsChannelsConfig"),
  "verification": t.opt("VerificationConfig"),
  "guildRequirements": t.opt("GuildRequirementsConfig"),
  "inactivity": t.opt("InactivityConfig"),
  "skyblockEvents": t.opt("SkyblockEventsConfig"),
  "hypixelUpdates": t.opt("HypixelUpdatesConfig"),
  "bridges": t.opt(t.array("BridgeConfig")),
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneralConfig,
  StaticDiscordConfig,
  PrometheusConfig,
  WebConfig,
  StatsChannelConfig,
  StatsChannelsConfig,
  VerificationRoleConfig,
  LevelRole,
  VerificationConfig,
  GuildRequirementsThresholds,
  GuildRequirementsConfig,
  InactivityConfig,
  SkyblockEventsConfig,
  HypixelUpdatesConfig,
  BridgeConfig,
  ApplicationConfig,
};
export default exportedTypeSuite;
